name: Terraform Deployment - Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  terraform-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code to main and dev folder
      uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        path: dev

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init and Apply in main and dev folder
      run: |
        terraform init
        terraform apply -auto-approve
        cd dev
        terraform init
        terraform apply -auto-approve
